# Generated by Django 3.2 on 2020-09-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_to_seconds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entervaluesCTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('seconds', models.IntegerField()),
            ],
        ),
    ]
