# Generated by Django 3.2 on 2020-09-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_max_edge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entervaluesFME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.FloatField()),
                ('number2', models.FloatField()),
            ],
        ),
    ]
