# Generated by Django 3.2 on 2020-09-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_repeater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entervaluesTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('number', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=models.TextField(),
        ),
    ]
